services:
  mariadb:
    image: mariadb:latest
    container_name: order_service_db
    environment:
      MYSQL_ROOT_PASSWORD: 1998
      MYSQL_ROOT_USER: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1998
    ports:
      - "3307:3306"
    volumes:
      - db_service:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_service: